### ISSUE TITLE
How to attach overlay into game screen?

### ISSUE THREAD

**Issue by thgiang** [michel-pi/GameOverlay.Net#11]
I am seeing Example.cs
The function SetupInstance is defining width, height, position x, position y of "overlay window".

I want to automatic find position of "MyGame.exe" to show "overlay window". Is this possible?

Thank you.

**Comment by michel-pi** [comment]
Hey,
https://github.com/michel-pi/GameOverlay.Net/blob/master/Project/GameOverlay/Windows/StickyOverlayWindow.cs keeps track of it's parent window position and size.

The easiest way to get your parent window handle is:
System.Diagnostics.Process.GetProcessesByName("ProcessNameWithoutDotExe")[0].MainWindowHandle

**Comment by thgiang** [comment]
Thank you very much!
