### ISSUE TITLE
OverlayWindow thread issue

### ISSUE THREAD

**Issue by BerkanYildiz** [michel-pi/GameOverlay.Net#13]
Hi,

the OverlayWindow.Dispose() never returns, which cause my application to hang before exiting. I had to implement a timeout system for it.

**Comment by michel-pi** [comment]
Hey,
thank you for your report!

it does return. but it's pretty lazy.
i fixed a few things causing additional problems when disposing those classes.
if you call Dispose() yourself at some point it will not take that long.
the main problem is in the .ctor called on app exit.

I've updated the NuGet package.

you can close this issue if it is working for you.
