### ISSUE TITLE
Anti-aliasing

### ISSUE THREAD

**Issue by BerkanYildiz** [michel-pi/GameOverlay.Net#14]
Hi,

Is the "anti-aliasing" option really working ?
I'm drawing players bones and, it doesn't seems to be "corrected".

```csharp
this.Device           = new D2DDevice(new DeviceOptions()
{
	AntiAliasing  = true,
	Hwnd          = this.Window.WindowHandle,
	MeasureFps    = true,
	MultiThreaded = false,
	VSync         = false
});
```

![image](https://user-images.githubusercontent.com/15068742/45920633-6c43d200-bea7-11e8-8c49-85355bc525bc.png)

**Comment by michel-pi** [comment]
AntiAliasing is only turned on for text.
there is a side effect where antialiasing in per primitive mode changes colors and pixels to make them look smooth.
Your red color (0xFF) would more likely look like (0x77). thats why i removed it

**Comment by BerkanYildiz** [comment]
Ah, that's sad 😞 
Any other way to fix that, even if it's "hacky" ?
