### ISSUE TITLE
Bad position of text using D2Device.DrawText

### ISSUE THREAD

**Issue by xaviermonin** [michel-pi/GameOverlay.Net#18]
Hello,

The position of the text is incorrect when using `D2Device.DrawText`.
`D2Device.DrawTextWithBackground `works.

Reproduce the problem:
Set a value of X > Width / 2 or Y > Height / 2.
In Exemple.cs, add `device.DrawText("FPS: " + device.FramesPerSecond, device.Width * 2 / 3, device.Height * 2 / 3, _font, _redBrush);` after `device.DrawTextWithBackground("FPS: " + device.FramesPerSecond, 10, 10, _font, _redBrush, _blackBrush);`

Excepted result:
![drawtext bug](https://user-images.githubusercontent.com/5740369/47831147-984c5000-dd8f-11e8-8e15-eeaad22a65a8.png)

**Comment by amephisto** [comment]
`[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void DrawText(string text, Point location, D2DFont font, ID2DBrush brush)
        {
            if (!IsDrawing) throw new InvalidOperationException("Use BeginScene before drawing any primitives!");
            if (text == null) throw new ArgumentNullException(nameof(text));

            //_device.DrawText(text, text.Length, font,
                //new RawRectangleF(location.X, location.Y, Width - location.X, Height - location.Y), brush.GetBrush(),
                //DrawTextOptions.NoSnap, MeasuringMode.Natural);

            var layout = new TextLayout(_fontFactory, text, font, Width - location.X, Height - location.Y);

            _device.DrawTextLayout(location, layout, brush.GetBrush(), DrawTextOptions.NoSnap);
        }`

This should fix it.

**Comment by BerkanYildiz** [comment]
Would be nice if this was pushed to NuGet

**Comment by michel-pi** [comment]
I'll update it in some days (until saturday). I am quite busy atm and i am working on a new overlay with better windows and a d3d renderer (faster drawing)
