### ISSUE TITLE
Black background when draw Rect

### ISSUE THREAD

**Issue by thgiang** [michel-pi/GameOverlay.Net#19]
Thank you for create a usefull library but I have 2 issues, please help me.
![image](https://user-images.githubusercontent.com/9299251/50214925-21592e00-03b4-11e9-857f-243d971ebd41.png)

**Comment by michel-pi** [comment]
could you please provide a simple console app (just the Program.cs file) which reproduces the problem?

**Comment by thgiang** [comment]
I am so sorry because Issue 1. It is because I am call wrong function to draw.

About Issue 1. The function DrawText still is my issue. In temp, I use DrawTextWithBackground to draw text.

**Comment by thgiang** [comment]
A problem with Win 7 is: Transparent color become black screen. Because Win 7 disable transparent key. Use this .reg file to fix it. 
Open notepad, copy all, save to abc.reg file then run it.

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM]
"ColorizationOpaqueBlend"=dword:00000000

**Comment by michel-pi** [comment]
thank you! i did not know about this registry key.

The general fix was to enable the "Windows Aero" feature
