### ISSUE TITLE
Multi-Screen setup

### ISSUE THREAD

**Issue by Hirse** [michel-pi/GameOverlay.Net#20]
Thanks for this great tool. I'm using it for a research project and I like how easy it is to create a nice overlay on my desktop.
For the next step in my project, I would like to create overlays over multiple screens (physical monitors), but I struggling to achieve that. Considering I have a main screen in the middle and one more on either side.
How would I set up the coordinates of the `OverlayWindow` or should I use multiple windows?

**Comment by michel-pi** [comment]
Hey,
my best guess would be that this is only possible using PInvoke.

It was planned to implement Window (size, position...) and Monitor information into a class but i needed to drop these things to focus on my actual "job".

I believe you could use 
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getsystemmetrics
or
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-systemparametersinfoa
for this case. You can search (CTRL + F) on these pages for Monitor or Screen.

You will need to handle possible negative resolutions from the "logical" left monitor if you calculate a size or layout from these.
The Main screen has 0:0 coordinates on the upper left corner (if i remember rigth).

The OverlayWindow itself has no problem with moving in between different screens (even if one screen ends and another starts).

**Comment by Hirse** [comment]
Would it be better (or even possible) to have one OverlayWindow spanning over all screens or create one for each screen?

**Comment by michel-pi** [comment]
I just ran a quick test and found out that it doesnt make any difference.
You might even benefit a bit from just having one really big window.

I made modifications to the Basic example in this repository to fit my 2 monitor setup:
https://gist.github.com/michel-pi/15aefcdde845ba41738d84f86996a6f0
and it made no difference on the FPS counter at all.
See:
https://gist.github.com/michel-pi/15aefcdde845ba41738d84f86996a6f0#file-fullscreenexample-cs-L26
https://gist.github.com/michel-pi/15aefcdde845ba41738d84f86996a6f0#file-fullscreenexample-cs-L44
https://gist.github.com/michel-pi/15aefcdde845ba41738d84f86996a6f0#file-fullscreenexample-cs-L86
https://gist.github.com/michel-pi/15aefcdde845ba41738d84f86996a6f0#file-fullscreenexample-cs-L86
I changed the windows position and size, disabled vsync, made the overlay transparent and draw the image on the 1 monitor.

I got the size and position by using GetWindowRect(IntPtr.Zero)
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getwindowrect

**Comment by Hirse** [comment]
Great. Thank you for the help.

I have another question, but I'll open a separate issue as it is not related to a multi-screen scenario.
