### ISSUE TITLE
Make Overlay transparent? Or Greenscreen

### ISSUE THREAD

**Issue by RarePotato8DE** [michel-pi/GameOverlay.Net#22]
Hello,
I am using your nuGet package since its really easy and very cool, thanks for that.
But because I would like to use and show the overlay in a video, I would like to select the window of the overlay in the recording software, the problem is that the background is black, and because of that you can't see the game in the "back". Is there a way to make it transparent or at least green/blue screen?

[https://i.imgur.com/DOHJUxU.png](url)
https://i.imgur.com/DOHJUxU.png

Thanks for replay and maybe a good answer!
Have a good day

**Comment by michel-pi** [comment]
What operating system do you have and can you show a bit of code? (the drawing part)

**Comment by RarePotato8DE** [comment]
So isn't that normal?
I am using Windows 10.

This is some code:
`            window = new OverlayWindow(0, 0, 1920, 1080)
            {
                IsTopmost = true,
                IsVisible = true
                ,
                Title = "ClockOverlay"
                ,
                ClassName = "ClockOverlay"
            };

            graphics = new GameOverlay.Drawing.Graphics(IntPtr.Zero, window.Width, window.Height)
            {
                MeasureFPS = true,
                PerPrimitiveAntiAliasing = true,
                TextAntiAliasing = true,
                UseMultiThreadedFactories = false,
                VSync = true
            };

            window.CreateWindow();
            graphics.WindowHandle = window.Handle; // set the target handle before calling Setup()
            graphics.Setup();`

And here is how I draw:
`                graphics.BeginScene();
                graphics.ClearScene();
                graphics.DrawText(graphics.CreateFont("Microsoft Sans Serif", 18, true, false), graphics.CreateSolidBrush(RainbowColor.R, RainbowColor.G, RainbowColor.B, RainbowColor.A), 1830, 10, DateTime.Now.ToString("HH:mm:ss"));
                graphics.EndScene();`

Is that enoght code?
I hope it helps for you, thanks.

**Comment by michel-pi** [comment]
what graphics card do you have?

No thats not normal. The main purpose of it is to be transparent

**Comment by RarePotato8DE** [comment]
AMD RX580

**Comment by RarePotato8DE** [comment]
I mean, if I use it, its transparent, so on my screen I can see the clock, and my game, normally, but in the recording software the background is black

**Comment by michel-pi** [comment]
oh, then it's a failure of your recording software. i usually use OBS and the Desktop recording

**Comment by michel-pi** [comment]
do you use window recording?

**Comment by RarePotato8DE** [comment]
I use OBS too, but I fixed it, I have to use game capture instead of window, and then enable transparency ^^

**Comment by RarePotato8DE** [comment]
Danke dir trotzdem, und wirklich gutes projekt!
