### ISSUE TITLE
Text rendering performance

### ISSUE THREAD

**Issue by michel-pi** [michel-pi/GameOverlay.Net#24]
I originally switched to creating a new `TextLayout` every time in the [text rendering methods](https://github.com/michel-pi/GameOverlay.Net/blob/master/source/Drawing/Graphics.cs#L1678 "Graphics.cs#L1678") because their was a little bug (either in mine or SharpDX code) which let the renderer not draw or crash when using the DrawText method instead of the DrawTextLayout method.

I think this is no more an issue and can be changed if this provides better performance for text rendering.

Disclaimer: I assume that Direct2D just creates a TextLayout for you if you use the simpler methods.

**Comment by CorrM** [comment]
Updates .?

**Comment by michel-pi** [comment]
@CorrM i don't have much time to do this 😞
