### ISSUE TITLE
Overlay will not show over some full-screen games on specific computers

### ISSUE THREAD

**Issue by dragoonm** [michel-pi/GameOverlay.Net#28]
The overlay engine generally works very well but on some specific computers, the overlay will not show over some games when the game is in full-screen mode. 
It will show over the same game on most other computers and will show over the game if it is in windowed mode.

I can reproduce this issue consistently using the Lenovo Flex 2 - 15 laptop on Windows 10 running Rocket League from Steam and the sample project.

**Comment by michel-pi** [comment]
Hey,
it's not possible to display a window on top of the fullscreen application.
They always need to be in windowed mode.

By it's not possible i mean it's not really intended. Some windows like the TaskManager and Toast Notifications have this ability in the latest Windows 10 version. I did not had enough time to prove it but it looks like only special windows are allowed to do this.

**Comment by dragoonm** [comment]
Thanks for the reply.
Do you know how discord or steam do their overlays? It seems they always show over the game.
Do they inject their overlays into games?

**Comment by michel-pi** [comment]
Yes. Discord injects their overlay using SetWindowsHooksEx i think and steam games are normally loading it i guess.

**Comment by dragoonm** [comment]
Thanks for the info. I'll close the issue here then.
