### ISSUE TITLE
Understanding Graphics.MeasureFPS 

### ISSUE THREAD

**Issue by Hirse** [michel-pi/GameOverlay.Net#31]
`Graphics` has a property `MeasureFPS` that is set to `true` in the examples. I don't really understand what this does however.
In my application scenario, I don't care about knowing the actual FPS of the Overlay, but in order to reduce the required graphics power, I would like to limit the FPS (to maybe 30).
Do I need to set it to `true` or is it enough to set `FPS` on the `GraphicsWindow`?

**Comment by michel-pi** [comment]
just set the FPS in the `GraphicsWindow`.

They both run independent and `MeasureFPS` is there to assist you in displaying them.

**Comment by Hirse** [comment]
Thanks for the explanation. I think I can get away with leaving the default values for `Graphics` then.
