### ISSUE TITLE
It works on .net framework 4.0, but minimal is 4.5

### ISSUE THREAD

**Issue by antimYT** [michel-pi/GameOverlay.Net#33]

**Comment by michel-pi** [comment]
Do you have a good reason for still using .Net <4.5?

**Comment by antimYT** [comment]
.net 4.0 is set by default for win 7 users. sometimes they are lazy to install 4.5 or higher.

**Comment by michel-pi** [comment]
windows 7 support ends on the 14 january 2020.
People should update their systems rather than using a framework released back in 2011.

I am sorry but you can compile the library yourself if you need 4.0 support.

**Comment by michel-pi** [comment]
This has been added while i added support for multiple .Net Frameworks and the .Net Standard 2.0 😄
