### ISSUE TITLE
Set FPS

### ISSUE THREAD

**Issue by jacobawesome7** [michel-pi/GameOverlay.Net#35]
Hi, so I have a problem. I am writing code that makes a box appear over something, however when the object moves the box lags behind. I know this is because of the FPS but when I try changing it, it just says that its read only.

**Comment by michel-pi** [comment]
The renderer can not control your rendering loop. It can only count the frames it's rendering.

The `GraphicsWindow` and the `StickyWindow` offer you a dedicated rendering thread. Otherwise, you need to implement the FPS limit yourself.

**Comment by jacobawesome7** [comment]
Ok, how would I implement the FPS limit myself?

**Comment by michel-pi** [comment]
This is a pretty easy way to accomplish this if you don't need accuracy https://github.com/michel-pi/GameOverlay.Net/blob/master/source/Windows/GraphicsWindow.cs#L188

This can help you to lock your rendering to your monitors refresh rate https://github.com/michel-pi/GameOverlay.Net/blob/master/source/Drawing/Graphics.cs#L73
You don't need any sleeps using this method. The renderer will do everything for you.

**Comment by jacobawesome7** [comment]
Thanks, fixed it!
