### ISSUE TITLE
Does not work on release mode.

### ISSUE THREAD

**Issue by njbrown09** [michel-pi/GameOverlay.Net#39]
Either instantly or within a minute or two, my application crashes. Im using the sticky window. It only happens in release mode though, so i cant debug it.

**Comment by michel-pi** [comment]
Oh i didn't get notified about this issue (mail or something).
I use this in my application and it does not crash for me or my customers.
Could you provide more information like the exception message? Would be great 😄

**Comment by njbrown09** [comment]
Yes. I am running my app in 64 bit mode.

**Comment by njbrown09** [comment]
.net 4.7.2

**Comment by michel-pi** [comment]
i wasn't able to reproduce any problems. Can you share your code?
