### ISSUE TITLE
Draw Opacity Problem

### ISSUE THREAD

**Issue by CorrM** [michel-pi/GameOverlay.Net#40]
My problem is the opacity of the 2DBox
that's who i expect i will get a box with 75% opacity (I mean i can see what is behind that color with 25%)

i use something like that
```
// drawer is Gfx
// DraculaOrchid75 = gfx.CreateSolidBrush(System.Drawing.Color.FromArgb(255 / 100 * 75, 45, 52, 54).ToOverlayColor());

drawer.DrawBox2D(
    GuiCode.DrawUtils.Electromagnetic,
    GuiCode.DrawUtils.DraculaOrchid75,
    Rectangle.Create(titleRect.Left, titleRect.Top, titleRect.Width, titleRect.Height - 4f),
    1f);
```
```
public static GameOverlay.Drawing.Color ToOverlayColor(this System.Drawing.Color color)
{
    return new GameOverlay.Drawing.Color(color.R, color.G, color.B, color.A);
}
```

But what i get is just the color changed, i mean it's just go darker or lighter.
i Expect some thing like black color with some opacity, to see what behind.

**Comment by michel-pi** [comment]
Hey,
please provide more informations about the used .Net Framework and Windows version.

And does that also happen when you use a `GameOverlay.Drawing.Color` directly instead of converting from a (i guess) `GDI` color?

**Comment by CorrM** [comment]
And does that also happen when you use a GameOverlay.Drawing.Color directly instead of converting from a (i guess) GDI color?
Yes, it's same.

.Net Framework : Net 4.7.2
Win : Win 10 (Last Update)

**Comment by michel-pi** [comment]
Can you upload a litte example project with this happening? I can not reproduce it

**Comment by michel-pi** [comment]
@CorrM can i close this?
