### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by Azahet** [michel-pi/GameOverlay.Net#41]
In the examples could you add an example in multithreading?

**Comment by michel-pi** [comment]
of course. but i need some time to do it. i am quite busy within the next days.

Basically you need to set
`UseMultiThreadedFactories` https://github.com/michel-pi/GameOverlay.Net/blob/master/source/Drawing/Graphics.cs#L81 to true
(before you or the overlay calls `Setup` https://github.com/michel-pi/GameOverlay.Net/blob/master/source/Drawing/Graphics.cs#L144)

The only thing you need to do is to use `BeginScene`, `ClearScene` and `EndScene` in a synchronized manner.

Start your tasks or run your threads in between those
