### ISSUE TITLE
DrawImage Transparency Problem

### ISSUE THREAD

**Issue by yasha107** [michel-pi/GameOverlay.Net#42]
When I draw a image, with DrawImage the background never is transparent no matter what I do, I tried it with CreateImage from a path and from a MemoryStream, didn't try from Resources as it won't work for what I am using this

**Comment by michel-pi** [comment]
@yasha107
just saw your email so i quickly follow up...

1. Can you provide a code example?
2. Can you upload the image you are using?

The library is trying to guess the best format to use with your image. it would be great to have the actual image to debug the issue.

If you can not provide the exact image then please provide anothewr one where it isn't working aswell.

**Comment by yasha107** [comment]
`gfx.DrawImage(gfx.CreateImage("E:/Downloads/cross-shaped-target.png"), 0, 0);`

![cross-shaped-target](https://user-images.githubusercontent.com/10366336/70115555-253b9a00-1671-11ea-8d47-2baf3ca6f706.png)

**Comment by michel-pi** [comment]
Thank you!

There is indeed a problem with my image decoder.
DirectX reports several supported formats on my machine but it seems like the preferred one isn't working and thats why there is a fallback for standard RGB.

I will use your image to create a better algorithm picking the best supported image format.

And just to make sure... Youre not using this one liner in production? You will run out of memory pretty soon. Load the image only once and use it from there on.

**Comment by michel-pi** [comment]
But i will do it tomorrow 😪

**Comment by yasha107** [comment]
Nope, not using it like this, I do load it once. This one was just for showing a fast example of the issue

**Comment by michel-pi** [comment]
Well, unfortunately both `BitmapDecoder.DecoderInfo.PixelFormats` and `BitmapFrameDecode.PixelFormat` don't work in our case.
The first one returns only RGB formats (no alpha) and the second one returns an unsupported format.

I currently rely on the returned `PixelFormat[]` from the `Decoder`.

My only idea is to change this behaviour to use a bruteforce approach by enumerating a list of all supported formats while prefering the ones with higher `bits per pixel` and `alpha channel`.

I'll probably need another day to implement the sorting algorithm, caching and loop.
Performance wise i see no problem when images get pre loaded. Support for the alpha channel and all different image formats is worth it i guess.

Here a picture of your image drawn with transparency.

![Overlay drawing transparent image](https://media.wtf/68245119.png)

**Comment by yasha107** [comment]
Perfect, would be very nice if this gets implemented)

**Comment by michel-pi** [comment]
@yasha107 
I uploaded a new NuGet package with the fixes applied.

I got good results when trying to load `png`, `bmp` and `gif` images.

If you got no more questions i will close the issue here.

**Comment by yasha107** [comment]
Thanks! Works very well now))
