### ISSUE TITLE
Drawing Image Make it looks darker

### ISSUE THREAD

**Issue by CorrM** [michel-pi/GameOverlay.Net#46]
Drawing Image Make it looks darker
That's image, when i try to draw it, is's go darker!

So what the problem !!
```
drawer.CreateImage("Path to image");
```
![Helmet-lvl-3](https://user-images.githubusercontent.com/5868825/72067155-d249a800-32ea-11ea-8620-dbe01cd84aa6.png)

**Comment by michel-pi** [comment]
i fixed the issue and uploaded the package. it should be available for download in less than one hour.

**Comment by CorrM** [comment]
I will test tomorrow, and let u know if there any problem.

**Comment by CorrM** [comment]
Fixed ❤️
