### ISSUE TITLE
AsyncDrawing

### ISSUE THREAD

**Issue by CorrM** [michel-pi/GameOverlay.Net#48]
There is any kind of Async, Mutlithread Drawing .?

Something like drawing in parallel

**Comment by Azahet** [comment]
https://github.com/michel-pi/GameOverlay.Net/issues/41

**Comment by michel-pi** [comment]
I still did not find the time to do a tutorial.

#41 summarizes it a bit.

Your loop should look like this:

pseudo
```
BeginScene();
ClearScene();

Tasks.RunAll(drawingTasks);
WaitAll(drawingTasks);

EndScene();
```
