### ISSUE TITLE
What new in 4.1.0

### ISSUE THREAD

**Issue by CorrM** [michel-pi/GameOverlay.Net#52]
What new in 4.1.0 .?

**Comment by michel-pi** [comment]
The Graphics class now has an event to recreate brushes and images when the device has an error.
https://michel-pi.github.io/GameOverlay.Net/api/GameOverlay.Drawing.Graphics.html#events

This is also useful when you need to recreate the device after your changed the target window.
https://michel-pi.github.io/GameOverlay.Net/api/GameOverlay.Drawing.Graphics.html#GameOverlay_Drawing_Graphics_Recreate_System_IntPtr_

Overlay windows (all classes that inherit) now have a single virtual Create and Join method.
https://michel-pi.github.io/GameOverlay.Net/api/GameOverlay.Windows.OverlayWindow.html#GameOverlay_Windows_OverlayWindow_Create
https://michel-pi.github.io/GameOverlay.Net/api/GameOverlay.Windows.OverlayWindow.html#GameOverlay_Windows_OverlayWindow_Join

Windows may also be recreated now https://michel-pi.github.io/GameOverlay.Net/api/GameOverlay.Windows.OverlayWindow.html#GameOverlay_Windows_OverlayWindow_Recreate

There are many new helper methods exported in the window helper class https://michel-pi.github.io/GameOverlay.Net/api/GameOverlay.Windows.WindowHelper.html

And the FPS counter in the Graphics class is now more accurate.

**Comment by CorrM** [comment]
Thatnks for this improves.
