### ISSUE TITLE
Listen for clicks

### ISSUE THREAD

**Issue by fritz-net** [michel-pi/GameOverlay.Net#53]
Is there a possibility to get clicks in the overlay area? At the moment the overlay is click trough, however if i want to implement interactions with the overlay I have to listen for clicks to change visuals, etc.
Is there a possibility to do so? I did not found anything in the documentation/example.

**Comment by michel-pi** [comment]
The Overlay window does not receive any MouseMove, MouseClick, KeyDown/Up events.

I normally have a windows forms or wpf gui where the user can make their settings.
This would be the best and easiest way in my opinion.

You could still manually get the key states each frame and react on that.
I have made this library https://github.com/michel-pi/InputManager.Net which can get all button states at once using https://michel-pi.github.io/InputManager.Net/api/InputManager.KeyboardState.html

The only thing this library currently not supports is the mouse position.

**Comment by michel-pi** [comment]
The required native functions for mouse positions are

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getcursorpos
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-screentoclient
