### ISSUE TITLE
Hidden Wpf Mainwindow

### ISSUE THREAD

**Issue by RNG42** [michel-pi/GameOverlay.Net#59]
The WPF windows seem to be hidden, how do i bring them back? Thanks in advance!

**Comment by michel-pi** [comment]
What WPF window do you mean? This library does not use WPF

**Comment by RNG42** [comment]
Thanks for the fast repIy. I added GameOverlay.Net to a Wpf Project, which works fine. Nonetheless it seems that no WPF window can be created at all. Just wanted to have a separate window with settings to adjust some values for the GameOverlay. Is there a better way to do so?

**Comment by michel-pi** [comment]
I also use a WPF window for my settings and just do the drawing stuff in the overlay window.
The problem must be on your side i believe.

**Comment by RNG42** [comment]
The only thing i did was adding the Example.cs and running it by the using statement in a blank project. 
`            using (var example = new Example(localByName[0].MainWindowHandle))
            {
                example.Run();
            }`
It still does not seem to work to add a new separate window. They do not show up somehow.

**Comment by michel-pi** [comment]
the `Example.Run()` method blocks the execution of the current thread. Look at the source code.
You do not need to use the `Join` method in your application

**Comment by RNG42** [comment]
Okay that seems to work, the windows do show up, but the Overlay is gone.

**Comment by michel-pi** [comment]
You still need to "Run" it. This is the line you should remove in the run method.
https://github.com/michel-pi/GameOverlay.Net/blob/master/source/Examples/Example.cs#L170

**Comment by RNG42** [comment]
The only thing i did was exactly this. I removed the line and after that the WPF window show up on application start, but not the Overlay itself since i removed the line above

**Comment by michel-pi** [comment]
i can test it myself tomorrow. but i am quite sure it does work

**Comment by michel-pi** [comment]
I just created a new WPF project, added the NuGet package, added the Example.cs and removed the mentioned line. It definitely works

**Comment by RNG42** [comment]
Did it again the exact same way you discribed it, but got the same result as before unfortunately.  I'm running this Project on .NET 2.7.2 and used the latest NuGet package 4.2.0. Compiled it with VS 2019 on Windows 10. 

I really don't know why this happens, but as soon as the WPF window gets loaded, the Overlay is not running anymore. I added a Messagebox right after Run() to get info about IsVisible, IsTopmost and IsRunning etc. The Overlay is runnung until this point, but after hitting Ok the Overlay disappears and the WPF Window shows up. The variable IsRunning changed to false after that. When trying to Unpause the GraphicsWindow at this state i get the exception: "Graphics window is not running". So it seems that the Graphics window stops the exact same moment the WPF window is loaded.

**Comment by RNG42** [comment]
The Overlay GraphicsWindow seems to get immediately disposed when the Join() line is removed, so i commented out the following line: 
https://github.com/michel-pi/GameOverlay.Net/blob/master/source/Examples/Example.cs#L185

**Comment by michel-pi** [comment]
You should choose a better using scope then or dispose the object somewhere else without a using statement

**Comment by RNG42** [comment]
Since i found out why the Overlay disappeared when a WPF window was shown, this can be considered as solved. Thanks for your help!
