### ISSUE TITLE
Huge Memory Leakage

### ISSUE THREAD

**Issue by themaoci** [michel-pi/GameOverlay.Net#61]
creating new ClassName() and floats int etc. inside functions which can be called in loops is forbidden to not cause memory leakage

usage of Simple DrawText in for loop 50 times using that in draw stickwindow causes 1 GB of memory usage after liek 2 minutes

GameOverlay.Drawing.Graphics.DrawText() is a function used in that example

```cs
public void DrawText(Font font, float fontSize, IBrush brush, float x, float y, string text)
{
	if (!this.IsDrawing)
	{
		throw ThrowHelper.UseBeginScene();
	}
	if (text == null)
	{
		throw new ArgumentNullException("text");
	}
	if (text.Length == 0)
	{
		return;
	}
	float num = (x < 0f) ? ((float)this.Width + x) : ((float)this.Width - x);// Memory leak
	float num2 = (y < 0f) ? ((float)this.Height + y) : ((float)this.Height - y);// Memory leak
	if (num <= fontSize)
	{
		num = (float)this.Width;
	}
	if (num2 <= fontSize)
	{
		num2 = (float)this.Height;
	}
	TextLayout textLayout = new TextLayout(this._fontFactory, text, font.TextFormat, num, num2);// Memory leak
	if (fontSize != font.FontSize)
	{
		textLayout.SetFontSize(fontSize, new TextRange(0, text.Length));// Memory leak
	}
	this._device.DrawTextLayout(new RawVector2(x, y), textLayout, brush.Brush, 2); // Memory leak
	textLayout.Dispose();
}
```

**Comment by michel-pi** [comment]
This does not cause a memory leak. You must be doing something else wrong

**Comment by michel-pi** [comment]
You don't seem to know how memory allocation in .Net works.

My library doesn't offer a `DrawTextWithOutline` method.
You must be doing a mistake there.

**Comment by themaoci** [comment]
i was using that to draw 3 texts
as 
gfx.DrawText(font, color, x, y, text);

and after rewriting your dll and caching soem shit i have no memory usage more then 50 MB
https://imgur.com/a/n1zcwmB

but i still didnt rewrite font alocation was thingking to make like temporary list of fonts alocated and grab them from there or something like that ...

you can close that :) issue i solve that by revriting your dll and cache some thigns in my drawing section (aka making template for colors and fonts to use later on

**Comment by michel-pi** [comment]
Your issue probably was that you don't dispose any resources and create your stuff in a loop. It's not the fault of the library
