### ISSUE TITLE
Use BeginScene before drawing anything

### ISSUE THREAD

**Issue by V3rzeT** [michel-pi/GameOverlay.Net#66]
Getting a System.InvalidOperationException: 'Use BeginScene before drawing anything' error.
I am trying to use multi threaded rendering.

This is my code:
```vbnet
    Private Sub ThreadWork(ByVal gfx As Graphics)
        gfx.BeginScene()

        gfx.DrawText(_fonts("arial"), _brushes("red"), New Point(10, 10), "FPS: " & gfx.FPS)

        gfx.EndScene()
    End Sub

    Private Sub _window_DrawGraphics(ByVal sender As Object, ByVal e As DrawGraphicsEventArgs)
        ThreadPool.QueueUserWorkItem(New WaitCallback(AddressOf ThreadWork), e.Graphics)
    End Sub
```

Am I doing something wrong or is it a bug?

**Comment by michel-pi** [comment]
The GraphicsWindow event already prepares the scene for you and runs on a separate thread.
You do not need to start an extra thread.

If you still want to use a different thread then consider a synchronization method to wait for it's completion inside the event.
