### ISSUE TITLE
Align Text/Font to horizontal center?

### ISSUE THREAD

**Issue by QuiNz0r** [michel-pi/GameOverlay.Net#67]
Am I missing something or is it not possible to set the Text alignment? it's always bound to left for me.

Thanks in advance

**Comment by michel-pi** [comment]
You need to align the text yourself inside the parent object.
You can use Graphics.MeasureString to calculate the size (width and height) of the text.

Transformations may be applied to the text to tilt it.

**Comment by QuiNz0r** [comment]
Thanks! Graphics.MeasureString was what I was missing works perfectly

offtopic question: any idea if BE cares about sharpdx overlays? I guess stickyoverlay with BypassTopmost is the best bet since they check for the topmost flag

**Comment by michel-pi** [comment]
I believe they do.
You would need to find a way around yourself.
