### ISSUE TITLE
calling DrawGraphics method in own thread

### ISSUE THREAD

**Issue by QuiNz0r** [michel-pi/GameOverlay.Net#68]
Thanks for this awesome project, works really well for me so far just having one more question:

I would like to loop the DrawGraphics method in my own thread instead of having it called by the DrawGraphics event, how would I achieve this?

Thanks in advance

**Comment by QuiNz0r** [comment]
nevermind, I initialized it wrong, after reading more into it I solved my issues. Great Project!

**Comment by QuiNz0r** [comment]
Sorry to bother you but I still have issues, I try to run an overlay without locking my main application but I always get a stackoverflowexception except when I run it in my own thread but then I get horrible rendering fps.

When I create I winform c# app and create the instance of my GraphicsWindow class my app get's locked so I guess you have to run the gameoverlay drawing in your own thread or am I missing something?

`private Example example = new Example()`

when I assign the reference later and call the Run() method my app get's locked too?

Is there any example how you're supposed to run the overlay without locking your main app? :) 

Thanks in advance

**Comment by QuiNz0r** [comment]
Okay so it was the Thread.Join() in the Run() obviously and for the low fps I iterated over an object which got locked() now everything runs quiet smooth at 30fps :) thanks again,  let me know if I can donate you some btc

**Comment by michel-pi** [comment]
Glad you found it by yourself.

Feel free to take the window code and implement something yourself if the default drawing loop doesn't fit your needs.

I am always happy to see some interest in the project. The Bitcoin address in the readme is still correct if you want to leave a buck.
