### ISSUE TITLE
The api overwrites font and color

### ISSUE THREAD

**Issue by Lucario443** [michel-pi/GameOverlay.Net#69]
I used to be able to set forecolor to `Color.Red`, however it now errors.
I used to be able to do `New Font("Arial", 20)`, but now it errors.

Is there a way to make it not use the common namespaces, or a way to retrieve the original color and font stuff?
I'm using visual basic.

**Comment by michel-pi** [comment]
You are supposed to use the builtin types. i don't want to include windows forms or wpf dependencies.

you can use the helper methods to create brushes and fonts https://github.com/michel-pi/GameOverlay.Net/blob/master/source/GameOverlay/Drawing/Graphics.cs#L271

Also, there is no such constructor for a `Font` in my library.
