### ISSUE TITLE
CPU Profile of EndScene() & MultiThreading

### ISSUE THREAD

**Issue by mentorfloat** [michel-pi/GameOverlay.Net#70]
I am trying to setup MultiThreadedFactories and I noticed that `gfx.EndScene();` uses much more CPU unit than other Draw methods. In comparison, setting `UseMultiThreadedFactories = false` and removing `gfx.BeginScene();` and `gfx.EndScene();` actually result in a better CPU usage profile. 

Version 1: better CPU profile
```csharp
private void Window_DrawGraphics(object sender, DrawGraphicsEventArgs e)
{
   var gfx = e.Graphics;
   gfx.ClearScene();

   CheckDrawText(gfx); // Contains DrawTextWithBackground
   CheckDrawCD(gfx); // Contains FillRectangle and FillCircle
}
```
Version 2: worse CPU profile with `UseMultiThreadedFactories = true`
```csharp
private void Window_DrawGraphics(object sender, DrawGraphicsEventArgs e)
{
   var gfx = e.Graphics;
   gfx.BeginScene();
   gfx.ClearScene();

   var tasks = new List<Task>();
   tasks.Add(CheckDrawTextAsync(gfx));
   tasks.Add(CheckDrawCDAsync(gfx));
   Task.WhenAll(tasks);

   gfx.EndScene(); // This consume the most CPU unit
}
```

The whole starting point is that I am trying to optimize the overlay, because for some reason **when the overlay is shown with `OverlayWindow.Show()`, the in-game FPS immediately dropped from 140 to 80 FPS**. I am only rendering 4 or 5 words, which should cost a negligible resource. This FPS-drop situation is true regardless of the above versions.
Please elaborate.

**Comment by michel-pi** [comment]
https://github.com/michel-pi/GameOverlay.Net/blob/master/source/GameOverlay/Windows/GraphicsWindow.cs#L237
