### ISSUE TITLE
FPS Magic

### ISSUE THREAD

**Issue by Yarik124421** [michel-pi/GameOverlay.Net#73]
Greetings, my program has a small audience that uses your library. About 5 out of 50 people have this problem. I don’t know if it’s connected or not. But after updating Windows, this problem also appeared for me. The problem itself: the frame limit is not working correctly. For example, I used an example from the repository and in it I have the same problem, so I dropped the problem of my code
If I set the fps limit to 60, fps fluctuates from 30 to 45 completely by accident
```
_window = new GraphicsWindow(0, 0, 800, 600, gfx)
			{
				FPS = 60,
				IsTopmost = true,
				IsVisible = true
			};
```
![image](https://user-images.githubusercontent.com/42224678/104857108-55063980-5927-11eb-953f-61b7569cd633.png)

If i change fps limit to any value 100-200 then fps is always in the 63-65 range
![image](https://user-images.githubusercontent.com/42224678/104857160-91399a00-5927-11eb-8b60-f5f5e31895b4.png)

If FPS = 500 75-150
![image](https://user-images.githubusercontent.com/42224678/104857191-c1813880-5927-11eb-8d10-88af815e934b.png)
The problem, as I understand it, somehow depends on the assembly of Windows, since I got it after updating to 20H2, among other users there were rare complaints before on completely different systems. Any idea which way to dig? On my laptop, the specified FPS is stable, but on the PC it is not at all the same

**Comment by michel-pi** [comment]
I suppose this also happens with the example code (screenshots).
Did you change any of the window initialization besides the fps?

I also got the recent update. I could try to let it run for a longer period to see if it randomly drops.

Otherwise, you may be able to debug it using the code in the repo.

**Comment by Yarik124421** [comment]
I just cloned the repository now and compiled without changing anything, the FPS is also not immediately stable
![image](https://user-images.githubusercontent.com/42224678/104858195-ab2aab00-592e-11eb-85e4-93fb8193fb53.png)
FPS Limit = 60


FPS Limit = 100
![image](https://user-images.githubusercontent.com/42224678/104858280-f5ac2780-592e-11eb-81bb-6037aca53024.png)

**Comment by Yarik124421** [comment]
I'm not sure if this is only due to the update, since before that there were similar complaints from users, even before the appearance of the last Windows update. And I don't really understand what needs to be debugged in such a case. Therefore, I wrote for help to you

**Comment by Yarik124421** [comment]
Wow, I noticed very strange behavior, I have 2 monitors. I turned off the fps limit, and while the console is on 1 monitor, my fps freezes at 142, but as soon as I transfer it to the second monitor, my fps soars to ~ 1000, and if I return it back, again 142. But if the fps limit is enabled, then there is no difference from transfer between monitors. I will make a video

**Comment by Yarik124421** [comment]
https://user-images.githubusercontent.com/42224678/104858959-c8ae4380-5933-11eb-9283-e5940e780a2f.mp4
Okay, I think these are two different problems - on 1 monitor the fps does not rise above 142 due to the enabled G-Sync, disabling it is a fix and the fps is the same on both monitors. But the problem is that the fps is less than the limit remains regardless of the g sync

**Comment by michel-pi** [comment]
Interesting.

Maybe it's something like the DPI Awareness issue. I needed to disable or "bypass" DPI awareness for Direct2D.

It could be something like that detecting some monitor configuration.

I need to do some research about that. Are you in a hurry for a fix?

**Comment by Yarik124421** [comment]
I am currently dealing with this problem, but so far I can not understand anything. With the fact that the FPS is different on different monitors, this is completely different, and in principle it is not a problem. It's just that my second monitor, due to nvidia technologies, limits the frequency to 144 (142, I suppose it's just an error). But the problem with the fact that the FPS is lower than the FPS limit is rather strange. I am in no hurry to fix it, my program has the ability to adjust the fps limit at startup, for those who observe this problem, I just advised to raise the limit to 200 in order to have a stable 60 fps, this is of course a crutch but it works)

**Comment by Yarik124421** [comment]
For the sake of curiosity, I wrote down how many ms each frame lasts, it looks like if a frame does not have time to draw in 15-17 ms (1000/60), then it is skipped, since the time of the next frame always fluctuates 30-32, it is very similar to special frame skip that did not have time to render, I don't know

![image](https://user-images.githubusercontent.com/42224678/104920541-fb465380-59a8-11eb-9e5c-b1cac53f51db.png)

**Comment by michel-pi** [comment]
Pretty weird.

I can check both, monitor configuration and my fps calculation.

But I may only have time on weekend.

**Comment by Yarik124421** [comment]
Okay, I'll analyze the behavior more, if there is news, I'll let you know. If that I had the same monitors before, but at one point this started, magic)

**Comment by Yarik124421** [comment]
Yes, this is definitely a frame skip, and it's kind of very strange, a fps limit of 30-59 turns into a stable 33 frames, since it's unrealistic to draw 60 frames in 59 frames and ~ 50% of frames are skipped. As soon as we step over the 60 fps limit, weirdness begins. If we set the fps limit to 65, then only ~ 10% of frames will be skipped and we will get a stable 54 fps, and if we set the fps limit to 70, we will get a stable 64 fps, everything is very strange. I attach a video with measurements.

https://www.youtube.com/watch?v=jzdbn-5ypCQ

**Comment by Yarik124421** [comment]
It is noteworthy that by default this setting is described as "Use 3D application setting", that is, the program can somehow indicate which type of vertical sync pulse to use

**Comment by CrazyZhang666** [comment]
useing OverlayWindow,do not use GraphicsWindow

**Comment by mentorfloat** [comment]
I noticed this too. FPS is not exactly at the setting. I also noticed another issue, when 'Wait for Vertical Sync' is not ticked in League of Legends' in-game setting, the game will stutter badly when overlay is on and shown on top, even when the in-game FPS shown is high (75 - 100FPS).

Turning the 'Wait for Vertical Sync' in-game setting on will cap it at 75FPS, following the monitor refresh rate, and it will feel smooth, without stuttering.

**Comment by michel-pi** [comment]
well thats a common side effect. get a better pc or try different settings for graphics card or windows game mode

**Comment by Yarik124421** [comment]
That's right, this happens in some other applications without configuring vsync as I wrote above. However, this is definitely fixed if the monitor draws the game in full screen mode, and not in a window without a frame, but in this condition, as far as I understand, rendering is impossible. also, many applications do not have this behavior in windowed mode, but I could not find how it works

**Comment by Yarik124421** [comment]
in my case, the pc is powerful by the way, so the problem is somewhere at the level of system settings

**Comment by michel-pi** [comment]
Well there is a way to draw it on top of a full screen application under Windows 10.

I can search it or explain it for you later, and I can finally take a closer look at those issues tomorrow.

**Comment by michel-pi** [comment]
https://github.com/michel-pi/GameOverlay.Net/issues/71#issuecomment-729711804

Do this every time the game window changes its state (open, closed, hidden, minimized whatever you call it).

You can use the recreate methods of the overlay / renderer for this.

**Comment by mentorfloat** [comment]
> well thats a common side effect. get a better pc or try different settings for graphics card or windows game mode

It happened to a few of us who has a decent spec. I'm convinced that it has something to do with vertical sync, because if it's turned on in-game, it'll be smooth. The problem is, the game's FPS will be lowered, thus causing a delayed input. (Ie. even if monitor can only display 60 frames per second, if the game is at 144 FPS, it'll still help in terms of keyboard/mouse input.)

The challenge is to run the game at 144 FPS, without the stuttering with the overlay on.

This occurrence is with League of Legends again.

> [#71 (comment)](https://github.com/michel-pi/GameOverlay.Net/issues/71#issuecomment-729711804)
> 
> Do this every time the game window changes its state (open, closed, hidden, minimized whatever you call it).
> 
> You can use the recreate methods of the overlay / renderer for this.

That was when I raised the fullscreen query, to be honest I never got that snippet to work back, even with hotkeys, so I left it. I wonder if @Yarik124421 can give it a go and share your solution? Been hoping to make this work.

**Comment by michel-pi** [comment]
Well, I found the FPS issue. Will fix it by tomorrow.
I confirmed that the full screen overlay works with League of Legends when you use the exact snippet.

**Comment by michel-pi** [comment]
Apparently a Windows update (version 2004) has broken `Thread.Sleep` again. To set the high precision timers per process you need to call `GameOverlay.TimerService.EnableHighPrecisionTimers` on application start.

**Comment by Yarik124421** [comment]
Before:
![image](https://user-images.githubusercontent.com/42224678/112727920-cff65c80-8f35-11eb-906d-dfc0d25ec60a.png)
After:
![image](https://user-images.githubusercontent.com/42224678/112728122-b6094980-8f36-11eb-8d4d-2b83cb1dfda7.png)
It's work, I will send a donation to your bitcoin wallet, thanks for this project.

**Comment by Yarik124421** [comment]
Is this the right BTC wallet? I cannot send money to it, writes that it does not exist

**Comment by michel-pi** [comment]
`bc1qp6zc73vy8pmr6lfe4cxa6eqzvkuer9hrjwpzza` is correct

Does your wallet support those addresses? I can get a Legacy address for you.
`14ES7f4GB3vD1C8Faz6ywqTcdDevxZoMyY`

Other cryptos will work too.

**Comment by michel-pi** [comment]
i received your bitcoin, thank you very much :)
