### ISSUE TITLE
Bug in Geometry,cs

### ISSUE THREAD

**Issue by dhu6411** [michel-pi/GameOverlay.Net#74]
Dear Sir,
thank you for the great library!

There is a misalignment in function
`AddCurve(Point point, float radius, float rotationAngle = 0.0f)`
where it reads:
`ArcSize = radius > 179.0f ? ArcSize.Large : ArcSize.Small,`
which does not reflect the intention.
`ArcSize = rotationAngle >= 180.0f ? ArcSize.Large : ArcSize.Small,`
does.

Warm Regards
dhu6411

**Comment by michel-pi** [comment]
Thank you for your report.

I am sorry that I forgot to answer.

I am just too busy at the moment. will look into it soon
