### ISSUE TITLE
StickyWindow and sizing.

### ISSUE THREAD

**Issue by Nzap** [michel-pi/GameOverlay.Net#77]
Hi Michel and thanks for this library. I'm trying to add some squares to a game window using a StickyWindow and using notepad for testing. No matter what size I tell the StickyWindow to be it always takes up the entire size of the ParentWindowHandle, is this how it's suppose to work? I planned on creating a StickyWindow for each square I need with the size I need and at the coords I need. Should I instead be creating one transparent StickyWindow that takes up the whole game window and drawing each square within that one StickyWindow? And if so then what's the sizing used for if it always takes up the entire parents window anyway? Thanks.

`Process[] processes = Process.GetProcessesByName("notepad");
Console.WriteLine(processes[0].MainWindowHandle.ToString());
_window = new StickyWindow(100, 100, 200, 150)
{
  IsTopmost = true,
  IsVisible = true,
  ParentWindowHandle = processes[0].MainWindowHandle,
};`

**Comment by Nzap** [comment]
I've swapped it all to one StickyWindow and drawn everything I need on there instead of drawing seperate windows. Still curious about the size arguments for StickyWindow() though.

**Comment by michel-pi** [comment]
Yes it is supposed to take the entire parent window size. The client size of a window is its size subtracted any borders and the title bar.

Can you name the arguments you are curious about?

It is much better to just create a single window. You can manage the bounds of the rectangles yourself.

**Comment by Nzap** [comment]
The arguments I was curious about were the size and position args for `public StickyWindow(int x, int y, int width, int height)` if it's always going to take up the whole size and position of the parent anyway.

**Comment by michel-pi** [comment]
this constructor is inherited from the base class

**Comment by Nzap** [comment]
Thanks for the replies, I'm quite new to c# and this lib has helped a lot with my first project..

**Comment by michel-pi** [comment]
you can leave the issue open for a while if you may have any new questions. i will close it at some point when it's inactive
