### ISSUE TITLE
Almost full screen mode does not work on all PCs

### ISSUE THREAD

**Issue by Yarik124421** [michel-pi/GameOverlay.Net#83]
Hello, I found an issue that describes how to do something similar to support for full screen mode, this does work for most Windows 10 PCs, however, for a small number of users it does not work
In my case, I give my window the topmost parameter every frame like this and it works
![image](https://user-images.githubusercontent.com/42224678/123524581-0cbc2600-d6d4-11eb-939b-72c20dd13199.png)
However, there is a small number of all users who still cannot see the interface, Windows 10 assemblies are both new and old, so there are suspicions that this is some kind of system setting, maybe you have ideas? I also did the inclusion of blur (WindowHelper.EnableBlurBehind) as described in Issue #71  but it gave no result

**Comment by michel-pi** [comment]
It shouldn't be required to constantly force the window top most.

Your users need to be on an up-to-date Windows version.
I can not address this issue without more information, and it sounds like you are probably missing something.

**Comment by Yarik124421** [comment]
I do this constantly so as not to track the folding and unfolding of the game and it helps, on two PCs there are almost identical assemblies of Windows, but on one of them it does not work. I will try to find the problem, if there is news - I will report here

My winver: (fullscreen overlay works)
![image](https://user-images.githubusercontent.com/42224678/123560161-5d518300-d7a9-11eb-89af-698804d8e911.png)
One of user (dont work):
![image](https://user-images.githubusercontent.com/42224678/123560192-7d814200-d7a9-11eb-9cdf-b5e062ec7a16.png)

**Comment by Yarik124421** [comment]
There is new information, I will share it just in case, there is still no solution.
My assumption is that there are unofficial builds of Windows in which the parameter is activated that blocks such a rendering method. In the properties of each application there is a setting to disable full screen optimizations (RMB - Properties - Compatibility - Disable fullscreen optimizations). If you enable it, the overlay stops being drawn on top of the full-screen game. I think there is some parameter that turns off this optimization globally for the entire system

**Comment by michel-pi** [comment]
well, that's not an issue for me. either use windowed mode or apply/check those settings
