### ISSUE TITLE
Windows forms support

### ISSUE THREAD

**Issue by GamingVideo** [michel-pi/GameOverlay.Net#87]
Any example on how to add it to a windows forms? I tried and i failed multiple times appreciate if could get an example.

**Comment by michel-pi** [comment]
Show what you are doing. There is nothing wrong with the Overlay. It will work with WinForms

**Comment by GamingVideo** [comment]
But there’s no example to do it

**Comment by michel-pi** [comment]
no example needed it is exactly the same
