### ISSUE TITLE
ImGUI implementation

### ISSUE THREAD

**Issue by DeDavidDev** [michel-pi/GameOverlay.Net#88]
Hey, thank you for this amazing libary!
I would like to add an ImGUI-Menu to my overlay using a wrapper called 'ImGUI.NET.DirectX'. Do you have a rough idea on how to approach this? From what I understood I need get the pointer to the d2d-device in order to initialize ImGUI. Is there a way to get it somehow? 
Thanks!

**Comment by GamingVideo** [comment]
Yes please show example of this we need this!

**Comment by michel-pi** [comment]
No sorry
