### ISSUE TITLE
Exception thrown: using DrawImage(Image, Rectangle, Single, Boolean)

### ISSUE THREAD

**Issue by KiNGKiMO** [michel-pi/GameOverlay.Net#90]
Exception thrown: 'SharpDX.SharpDXException' in SharpDX

Using DrawImage(Image, Rectangle, Single, Boolean) or DrawImage(Image, Single, Single, Single, Single, Single, Boolean)

Thanks in advance.

**Comment by michel-pi** [comment]
Tell me the exception message and error code.
provide some code.
provide the image
