### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by Sgamzat05** [michel-pi/GameOverlay.Net#96]
when drawing a large number of labels, shapes, images, flickering begins
How can this be fixed? Maybe There is a double buffer?

**Comment by michel-pi** [comment]
It's not possible to help you without code.
The issue probably is that your code isn't executing fast enough and that cuts down the FPS.

**Comment by Sgamzat05** [comment]
Can i get u discord to share code?

**Comment by Sgamzat05** [comment]
or how to use multithreading?

**Comment by michel-pi** [comment]
Multi Threading isn't your issue.
I don't have discord.
You can consider refactoring your code. Do not recreate brushes, fonts and images in your loop. Re-use them.
Do not run computation heavy code in your drawing thread.

How many different shapes or figures are you drawing? How often do you call drawing methods in your loop? 100? 1000? 10000?
