### ISSUE TITLE
Possible Idea.

### ISSUE THREAD

**Issue by ImmuneLion318** [michel-pi/GameOverlay.Net#98]
Is it possible to for example have a variable such as
`public Graphics VisualGraphic;`
then on DrawGraphics set this variable to e.Graphics so then at any point I can call VisualGraphic.Draw whatever to draw stuff is it possible todo this or another way todo this with the overlay class.

**Comment by michel-pi** [comment]
No, that's not how rendering works. You need to start a frame and end a frame at some point. The renderer offers those methods. The overlay just utilizes them. You can see the source.
